# Generated by Django 5.0.1 on 2024-01-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='warehouse_c_name_6a31b4_idx'),
        ),
    ]
