# Generated by Django 4.2.5 on 2023-12-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0002_alter_menuitem_food_item'),
        ('warehouse', '0002_dish_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.category'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='warehouse.ingredient'),
        ),
    ]
