# Generated by Django 4.2.5 on 2023-12-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_delete_fooditem_ingredient_category_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='returnable',
            field=models.BooleanField(default=True),
        ),
    ]
