# Generated by Django 5.0.1 on 2024-01-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_ingredient_exp_ingredient_mfg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='mfg',
        ),
    ]
