# Generated by Django 4.2.5 on 2023-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_ingredient_returnable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='returnable',
            field=models.BooleanField(default=True),
        ),
    ]
