# Generated by Django 5.0.1 on 2024-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_ingredient_exp_ingredient_mfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='exp',
            field=models.DateField(blank=True, default='2025-04-04', null=True),
        ),
    ]
