# Generated by Django 5.0.1 on 2024-04-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_ingredient_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option', models.CharField(choices=[('CODE', 'Apply Code'), ('NO CODE', 'Apply Dish')], max_length=12)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dishes_discount', models.ManyToManyField(blank=True, related_name='discounts', to='warehouse.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='discounts_dish',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='warehouse.discount'),
        ),
    ]
