# Generated by Django 5.0.1 on 2024-04-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_dish_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='discounted_price',
        ),
    ]
