# Generated by Django 5.0.1 on 2024-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_dish_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
