# Generated by Django 5.0.1 on 2024-01-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booked', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
