# Generated by Django 5.0.1 on 2024-01-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0002_table_delete_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='phone_number',
        ),
    ]
