# Generated by Django 5.0.1 on 2024-01-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0003_remove_table_phone_number'),
        ('warehouse', '0006_ingredient_exp_ingredient_mfg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cooked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.dish')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_in_restaurant.table')),
            ],
        ),
    ]
