# Generated by Django 5.0.1 on 2024-04-09 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0004_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished_dishes',
            field=models.ManyToManyField(blank=True, related_name='orders_finished', to='eat_in_restaurant.queue'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_in_restaurant.order')),
            ],
        ),
    ]
