# Generated by Django 5.0.1 on 2024-04-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0005_order_finished_dishes_order_invoice_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='finished_dishes',
        ),
        migrations.AddField(
            model_name='order',
            name='finished_dishes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
