# Generated by Django 5.0.1 on 2024-06-27 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0006_remove_order_finished_dishes_order_finished_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=datetime.datetime(2024, 6, 27, 10, 24, 30, 643042, tzinfo=datetime.timezone.utc), max_length=255),
        ),
    ]
