# Generated by Django 5.0.1 on 2024-06-27 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0007_order_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_code',
        ),
        migrations.AddField(
            model_name='invoice',
            name='code_invoice',
            field=models.CharField(default=datetime.datetime(2024, 6, 27, 10, 48, 12, 894786, tzinfo=datetime.timezone.utc), editable=False, max_length=100, unique=True),
        ),
    ]
