# Generated by Django 5.0.1 on 2024-06-27 11:04

import eat_in_restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_in_restaurant', '0008_remove_order_order_code_invoice_code_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='code_invoice',
            field=models.CharField(default=eat_in_restaurant.models.generate_code_invoice, editable=False, max_length=100, unique=True),
        ),
    ]
