# Generated by Django 5.0.1 on 2024-04-09 06:15

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='012345678', max_length=20, validators=[restaurant.models.validate_phone_number]),
        ),
    ]
