# Generated by Django 5.0.1 on 2024-04-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tags',
        ),
    ]
