# Generated by Django 4.2.5 on 2023-12-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
