# Generated by Django 5.0.1 on 2024-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_cart', '0002_rename_order_ordercart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
